services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    restart: "no"
    env_file:
      - ./env/plex.env
    volumes:
      - ${FILE_DIR}:/media
      - ${DATA_DIR}/plex/config:/config
      - ${DATA_DIR}/plex/transcode:/transcode
    labels:
      # Traefik integration
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.rule=Host(`plex.${TRAEFIK_ACME_DOMAIN}`)"
      - "traefik.http.routers.plex.tls.certresolver=cloudflare"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.services.plex.loadbalancer.server.scheme=http"
      # Homepage integration
      - "homepage.group=Media"
      - "homepage.name=Plex"
      - "homepage.icon=plex.svg"
      - "homepage.href=https://plex.${TRAEFIK_ACME_DOMAIN}"
      - "homepage.description=Media Server"
    devices:
      - nvidia.com/gpu=${GPU_ID}
    deploy:
      resources:
        limits:
          memory: 2GB

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    restart: unless-stopped
    container_name: tautulli
    env_file:
      - ./env/plex.env
    depends_on:
      - plex
    networks:
      - proxy
    volumes:
      - ${DATA_DIR}/tautulli:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      # Traefik integration
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.entrypoints=websecure"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.${TRAEFIK_ACME_DOMAIN}`)"
      - "traefik.http.routers.tautulli.tls.certresolver=cloudflare"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
      # Homepage integration
      - "homepage.group=Media"
      - "homepage.name=Tautulli"
      - "homepage.icon=tautulli.svg"
      - "homepage.href=https://tautulli.${TRAEFIK_ACME_DOMAIN}"
      - "homepage.description=Plex Monitoring"
    deploy:
      resources:
        limits:
          memory: 512MB

networks:
  proxy:
    external: true
