services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1
    container_name: homepage
    restart: "no"
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=home.${TRAEFIK_ACME_DOMAIN}
    networks:
      - proxy
      - metrics
    volumes:
      - ${DATA_DIR}/homepage:/app/config
      - ${DATA_DIR}/homepage/icons:/app/public/icons
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.rule=Host(`home.${TRAEFIK_ACME_DOMAIN}`)"
      - "traefik.http.routers.homepage.tls.certresolver=cloudflare"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    deploy:
      resources:
        limits:
          memory: 512MB

  portainer:
    image: portainer/portainer-ce:alpine-sts
    container_name: portainer
    restart: "no"
    networks:
      - proxy
    volumes:
      - ${DATA_DIR}/portainer:/data
      - ${DOCKER_SOCK}:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      # Traefik integration
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`panel.${TRAEFIK_ACME_DOMAIN}`)"
      - "traefik.http.routers.portainer.tls.certresolver=cloudflare"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      # Homepage integration
      - "homepage.group=Core"
      - "homepage.name=Portainer"
      - "homepage.icon=portainer.svg"
      - "homepage.href=https://panel.${TRAEFIK_ACME_DOMAIN}"
      - "homepage.description=Container Management"
    deploy:
      resources:
        limits:
          memory: 512MB

  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: "no"
    security_opt:
      - no-new-privileges:true
    environment:
      # Cloudflare Zero DNS API token
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_dns_api_token
    networks:
      - proxy
      - metrics
    ports:
      - 80:80
      - 443:443
    secrets:
      - cf_dns_api_token
      - traefik_htpasswd
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${DATA_DIR}/traefik/acme.json:/etc/traefik/acme.json
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro
    command:
      # Traefik log level
      # Possible values: DEBUG, INFO, WARN, ERROR, FATAL
      # Default is INFO, but DEBUG is useful for troubleshooting
      - --log.level=${TRAEFIK_LOG_LEVEL}
      # Enable Docker as a provider
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      # Entry points
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Enable DNS challenge
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.propagation.delayBeforeChecks=45s
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      # ACME configuration for Let's Encrypt
      - --certificatesresolvers.cloudflare.acme.caserver=${TRAEFIK_ACME_SERVER}
      - --certificatesresolvers.cloudflare.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.cloudflare.acme.storage=/etc/traefik/acme.json
      # Enable Prometheus metrics
      - --metrics.prometheus=false
      - --metrics.prometheus.entrypoint=metrics
      # API access from localhost only
      - --api.insecure=true
    labels:
      # Global middleware for HTTP to HTTPS redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/run/secrets/traefik_htpasswd"
      # Traefik dashboard router
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.middlewares=traefik-auth@docker"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${TRAEFIK_ACME_DOMAIN}`)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      # Homepage integration
      - "homepage.group=Core"
      - "homepage.name=Traefik"
      - "homepage.icon=traefik.svg"
      - "homepage.href=https://traefik.${TRAEFIK_ACME_DOMAIN}"
      - "homepage.description=Reverse Proxy & Dashboard"
      - "homepage.widget.type=traefik"
      - "homepage.widget.url=http://traefik:8080"
    deploy:
      resources:
        limits:
          memory: 512MB

secrets:
  cf_dns_api_token:
    file: ./secret/cf_dns.secret
  traefik_htpasswd:
    file: ./secret/htpasswd.secret

networks:
  proxy:
    external: true
  metrics:
    external: true
